### ISSUE TITLE
Progamei em java. será que vou pro inferno?

### ISSUE THREAD

**Issue by alysson3dev** [ospilhacheia/tretadev#20]

**Comment by brunowego** [comment]
Cara se for, não vai ta sozinho.

**Comment by Joshaby** [comment]
Vai pro céu, e lá tem um cantinho do amor só pra quem programa em Java!

**Comment by PabloEmidio** [comment]
A biblia diz que bem aventurados os que sofrem.. Então quem programa em java deveria ir para o céu. Mas como? Se java é algo enviado dos infernos

**Comment by obrennomartins** [comment]
Bem-aventurados os pobres de espírito, porque deles é o reino dos céus;

Mateus 5:3

**Comment by terremoth** [comment]
Você não vai pro inferno, você o ajudou a ser construído
