### ISSUE TITLE
Daily é chato ou não?

### ISSUE THREAD

**Issue by JessicaNathany** [ospilhacheia/tretadev#22]

**Comment by jmurowaniecki** [comment]
Tô tentando entender o motivo dessa thread magnífica estar fechada.

A daily é o melhor momento pra colocar as fofocas em dia… Melhor ainda que é um tempo perdido **mas REMUNERADO**.

![Captura de tela de 2021-08-11 19-28-41](https://user-images.githubusercontent.com/1261167/129111988-3ccaffa8-033c-44ac-a5a7-0b1a2af4b96c.png)
